/**
 * @file test.js generated by Gemini 2.5 Pro AI to test rcv-core-logic Ranked Choice Voting library.
 * @description
 * A simple test suite for the rcv-core-logic library.
 * Run this file using `node test.js` in your terminal.
 * You can also add "test": "node test.js" to the "scripts" section of your package.json and run npm test
 */

// Import the functions to be tested
// The './' is important – it tells Node to look for a local file.
const { validateVote, formatBallots, tally } = require('./index.js');

// A simple test runner helper
let testCount = 0;
let passCount = 0;

function test(description, testFunction) {
  testCount++;
  try {
    testFunction();
    passCount++;
    console.log(`\x1b[32m  ✔ PASS:\x1b[0m ${description}`); // Green text for pass
  } catch (error) {
    console.error(`\x1b[31m  ✖ FAIL:\x1b[0m ${description}`); // Red text for fail
    console.error(error);
  }
}

// Helper for deep equality check (simple version)
function assertEqual(actual, expected, msg) {
  const actualJson = JSON.stringify(actual);
  const expectedJson = JSON.stringify(expected);
  if (actualJson !== expectedJson) {
    throw new Error(
      `${msg}\n    Expected: ${expectedJson}\n    Got:      ${actualJson}`
    );
  }
}

// ---------------------------------
// 1. validateVote() Tests
// ---------------------------------
console.log('\nRunning tests for validateVote()...');
const TEST_CANDIDATES = ['A', 'B', 'C'];

test('should return valid for a correct ballot', () => {
  const ballot = ['A', 'C', 'B'];
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(result, { valid: true, error: null }, 'Valid ballot failed');
});

test('should return invalid for a duplicate candidate', () => {
  const ballot = ['A', 'B', 'A'];
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(
    result,
    {
      valid: false,
      error: 'Duplicate found: ballot contains repeated option rankings.',
    },
    'Duplicate candidate check failed'
  );
});

test('should return invalid for an unknown candidate', () => {
  const ballot = ['C', 'D', 'A'];
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(
    result,
    {
      valid: false,
      error: `Invalid choice: "D" is not one of the options.`,
    },
    'Unknown candidate check failed'
  );
});

test('should return valid for a partial ballot', () => {
  const ballot = ['B', 'A'];
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(result, { valid: true, error: null }, 'Partial ballot failed');
});

test('should return invalid for a ballot containing a non-string choice', () => {
  const ballot = ['A', 123, 'C']; // 123 is a number, not a string
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(
    result,
    {
      valid: false,
      error: 'Invalid choice: ballot contains a non-string value.',
    },
    'Non-string choice check failed'
  );
});

// ---------------------------------
// 2. formatBallots() Tests
// ---------------------------------
console.log('\nRunning tests for formatBallots()...');

test('should filter out invalid and malformed ballots', () => {
  const rawVotes = [
    { userId: 'u-1', rankings: ['A', 'B'] }, // Valid
    { userId: 'u-2', rankings: ['B', 'A', 'B'] }, // Invalid (duplicate)
    { userId: 'u-3', rankings: ['C'] }, // Valid
    { userId: 'u-4', rankings: ['D'] }, // Invalid (unknown)
    { userId: 'u-5', rankings: ['A', 'C'] }, // Valid
    { userId: 'u-6', otherProp: 'foo' }, // Malformed (no .rankings)
    null, // Malformed (null vote)
  ];
  const expected = [
    ['A', 'B'],
    ['C'],
    ['A', 'C'],
  ];
  const skipped = [];
  const result = formatBallots(rawVotes, TEST_CANDIDATES, (vote, error) =>
    skipped.push([vote && vote.userId, error])
  );
  assertEqual(result, expected, 'Ballot formatting failed');
  assertEqual(
    skipped,
    [
      ['u-2', 'Duplicate found: ballot contains repeated option rankings.'],
      ['u-4', 'Invalid choice: "D" is not one of the options.'],
      ['u-6', 'Vote is not an object with a rankings array.'],
      [null, 'Vote is not an object with a rankings array.'],
    ],
    'onInvalid was not called for each skipped vote'
  );
});

test('should not write to the console when skipping ballots', () => {
  const originalWarn = console.warn;
  let warned = false;
  console.warn = () => { warned = true; };
  try {
    formatBallots([{ rankings: ['D'] }], TEST_CANDIDATES);
  } finally {
    console.warn = originalWarn;
  }
  assertEqual(warned, false, 'formatBallots wrote to console.warn');
});

test('should return an empty array for empty input', () => {
  const result = formatBallots([], TEST_CANDIDATES);
  assertEqual(result, [], 'Empty input did not return empty array');
});

// ---------------------------------
// 3. tally() Tests
// ---------------------------------
console.log('\nRunning tests for tally()...');
const TEST_CONFIG = {
  tieBreaking: 'eliminate_all',
  maxRounds: 10,
};

test('should find a winner in a single round (clear majority)', () => {
  const ballots = [
    ['A', 'B', 'C'],
    ['A', 'C', 'B'],
    ['B', 'A', 'C'],
    ['A', 'B', 'C'],
  ];
  const results = tally(ballots, TEST_CANDIDATES, TEST_CONFIG);
  assertEqual(results.winner, 'A', 'First-round winner test failed');
  assertEqual(results.rounds.length, 1, 'First-round winner test had >1 round');
  assertEqual(
    results.rounds[0].tally,
    { A: 3, B: 1, C: 0 },
    'First-round tally incorrect'
  );
});

test('should find a winner in multiple rounds (elimination)', () => {
  // This is the example from the README
  const ballots = [
    ['A', 'B', 'C'],
    ['B', 'A', 'C'],
    ['A', 'C', 'B'],
    ['C', 'B', 'A'],
    ['B', 'A', 'C'],
  ];
  const candidates = ['A', 'B', 'C'];
  const results = tally(ballots, candidates, TEST_CONFIG);

  assertEqual(results.winner, 'B', 'Multi-round winner incorrect');
  assertEqual(results.rounds.length, 2, 'Multi-round election rounds incorrect');
  // Check Round 1
  assertEqual(
    results.rounds[0].status,
    'Elimination',
    'Round 1 status incorrect'
  );
  assertEqual(
    results.rounds[0].eliminated,
    ['C'],
    'Round 1 elimination incorrect'
  );
  // Check Round 2
  assertEqual(
    results.rounds[1].status,
    'Winner found',
    'Round 2 status incorrect'
  );
  assertEqual(
    results.rounds[1].tally,
    { A: 2, B: 3 },
    'Round 2 tally incorrect'
  );
});

test('should handle an unbreakable tie', () => {
  const ballots = [
    ['A', 'B'],
    ['B', 'A'],
  ];
  const candidates = ['A', 'B'];
  const results = tally(ballots, candidates, TEST_CONFIG);
  assertEqual(results.winner, null, 'Tie test did not result in null winner');
  assertEqual(
    results.rounds[results.rounds.length - 1].status,
    'Unbreakable tie',
    'Tie test status incorrect'
  );
});

test('should handle exhausted ballots correctly', () => {
  const ballots = [
    ['A', 'B'],
    ['A', 'B'],
    ['B', 'A'],
    ['B', 'A'],
    ['C'], // This ballot will be exhausted after C is eliminated
  ];
  const candidates = ['A', 'B', 'C'];
  const results = tally(ballots, candidates, TEST_CONFIG);

  // Round 1: Tally is {A: 2, B: 2, C: 1}. C is eliminated.
  // C's 1 vote is transferred to "exhausted".
  // Round 2: Tally is {A: 2, B: 2}. This is an unbreakable tie.
  assertEqual(results.winner, null, 'Exhausted ballot test winner incorrect');
  assertEqual(
    results.rounds.length,
    2,
    'Exhausted ballot test round count incorrect'
  );
  assertEqual(
    results.rounds[0].transfers.C.exhausted,
    1,
    'Did not correctly log exhausted ballot transfer'
  );
  assertEqual(
    results.rounds[1].status,
    'Unbreakable tie',
    'Exhausted ballot test did not end in a tie'
  );
});

test('should declare the last remaining option the winner when exhausted ballots block a majority', () => {
  const ballots = [['A'], ['A'], ['B'], ['C'], ['D']];
  const candidates = ['A', 'B', 'C', 'D'];
  const results = tally(ballots, candidates, TEST_CONFIG);

  // Round 1: {A: 2, B: 1, C: 1, D: 1}. B, C, D eliminated; their ballots exhaust.
  // Round 2: {A: 2}. A is below the threshold of 3 but is the only option left.
  assertEqual(results.winner, 'A', 'Sole remaining option was not declared winner');
  assertEqual(results.rounds.length, 2, 'Sole survivor test round count incorrect');
  assertEqual(results.rounds[1].status, 'Winner found', 'Sole survivor round status incorrect');
  assertEqual(results.rounds[1].eliminated, [], 'Sole survivor should not be eliminated');
});

test('should not declare a winner when the only option has no votes', () => {
  const results = tally([], ['A'], TEST_CONFIG);
  assertEqual(results.winner, null, 'Zero-vote sole option should not win');
});

test('should default maxRounds when config is omitted', () => {
  const ballots = [
    ['A', 'B', 'C'],
    ['B', 'A', 'C'],
    ['A', 'C', 'B'],
    ['C', 'B', 'A'],
    ['B', 'A', 'C'],
  ];
  const results = tally(ballots, ['A', 'B', 'C']);
  assertEqual(results.winner, 'B', 'Default config winner incorrect');
  assertEqual(results.error, undefined, 'Default config should not hit max rounds');
});

test('should measure the threshold against continuing ballots each round', () => {
  const ballots = [
    ['A'], ['A'], ['A'], ['A'],
    ['B'], ['B'], ['B'],
    ['C'], ['C'],
    ['D'],
  ];
  const results = tally(ballots, ['A', 'B', 'C', 'D'], TEST_CONFIG);

  // Round 1: 10 continuing, threshold 6. D eliminated, its ballot exhausts.
  // Round 2: 9 continuing, threshold 5. C eliminated, its ballots exhaust.
  // Round 3: 7 continuing, threshold 4. A has 4 and wins.
  assertEqual(results.winner, 'A', 'Continuing-ballot winner incorrect');
  assertEqual(results.threshold, 6, 'Top-level threshold should be the first-round threshold');
  assertEqual(results.rounds.length, 3, 'Continuing-ballot round count incorrect');
  assertEqual(
    results.rounds.map((r) => [r.threshold, r.exhausted]),
    [[6, 0], [5, 1], [4, 3]],
    'Per-round threshold/exhausted incorrect'
  );
});

test('should break a last-place tie using the previous round when configured', () => {
  const ballots = [
    ['A'], ['A'], ['A'],
    ['B', 'A'], ['B', 'C'],
    ['C'], ['C'], ['C'],
    ['D', 'B', 'A'],
  ];
  const candidates = ['A', 'B', 'C', 'D'];

  // Round 1: {A: 3, B: 2, C: 3, D: 1}. D eliminated, transfers to B.
  // Round 2: {A: 3, B: 3, C: 3}, a three-way tie.
  const eliminateAll = tally(ballots, candidates, TEST_CONFIG);
  assertEqual(eliminateAll.winner, null, 'eliminate_all should end in a tie');
  assertEqual(eliminateAll.rounds[1].status, 'Unbreakable tie', 'eliminate_all status incorrect');

  // previous_round: B had the fewest in round 1, so only B is eliminated.
  // Round 3: {A: 5, C: 4}. A wins.
  const previousRound = tally(ballots, candidates, { tieBreaking: 'previous_round' });
  assertEqual(previousRound.rounds[1].eliminated, ['B'], 'previous_round eliminated the wrong option');
  assertEqual(previousRound.winner, 'A', 'previous_round winner incorrect');
  assertEqual(previousRound.rounds[2].tally, { A: 5, C: 4 }, 'previous_round final tally incorrect');
});

test('should eliminate all tied options when no previous round separates them', () => {
  const ballots = [['A'], ['A'], ['A'], ['B'], ['C'], ['D']];
  const results = tally(ballots, ['A', 'B', 'C', 'D'], { tieBreaking: 'previous_round' });
  // Round 1: {A: 3, B: 1, C: 1, D: 1}, threshold 4. No earlier round exists,
  // so B, C and D are eliminated together and their ballots exhaust.
  // Round 2: A has 3 of 3 continuing ballots and wins.
  assertEqual(results.rounds[0].eliminated, ['B', 'C', 'D'], 'Round-1 tie fallback incorrect');
  assertEqual(results.winner, 'A', 'Round-1 tie fallback winner incorrect');
});

test('should reject an unknown tieBreaking rule', () => {
  let threw = false;
  try {
    tally([['A']], ['A', 'B'], { tieBreaking: 'coin_flip' });
  } catch (error) {
    threw = /Unknown tieBreaking rule "coin_flip"/.test(error.message);
  }
  assertEqual(threw, true, 'Unknown tieBreaking rule did not throw');
});

// ---------------------------------
// Final Summary
// ---------------------------------
console.log('\n---------------------------------');
console.log('         Test Summary');
console.log('---------------------------------');
console.log(`  Total Tests: ${testCount}`);
if (passCount === testCount) {
  console.log(`\x1b[32m  Passed:      ${passCount}\x1b[0m`); // Green
  console.log('\x1b[32m\n  All tests passed! ✨\x1b[0m');
} else {
  console.log(`\x1b[32m  Passed:      ${passCount}\x1b[0m`); // Green
  console.log(`\x1b[31m  Failed:      ${testCount - passCount}\x1b[0m`); // Red
  console.log('\x1b[31m\n  Some tests failed.\x1b[0m');
  process.exitCode = 1; // Fail `npm test` so CI does not publish a broken build
}
console.log('---------------------------------\n');