/**
 * @file test.js generated by Gemini 2.5 Pro AI to test rcv-core-logic Ranked Choice Voting library.
 * @description
 * A simple test suite for the rcv-core-logic library.
 * Run this file using `node test.js` in your terminal.
 * You can also add "test": "node test.js" to the "scripts" section of your package.json and run npm test
 */

// Import the functions to be tested
// The './' is important – it tells Node to look for a local file.
const { validateVote, formatBallots, drawTieBreakOrder, tally } = require('./index.js');

// A simple test runner helper
let testCount = 0;
let passCount = 0;

function test(description, testFunction) {
  testCount++;
  try {
    testFunction();
    passCount++;
    console.log(`\x1b[32m  ✔ PASS:\x1b[0m ${description}`); // Green text for pass
  } catch (error) {
    console.error(`\x1b[31m  ✖ FAIL:\x1b[0m ${description}`); // Red text for fail
    console.error(error);
  }
}

// Helper for deep equality check (simple version)
function assertEqual(actual, expected, msg) {
  const actualJson = JSON.stringify(actual);
  const expectedJson = JSON.stringify(expected);
  if (actualJson !== expectedJson) {
    throw new Error(
      `${msg}\n    Expected: ${expectedJson}\n    Got:      ${actualJson}`
    );
  }
}

// ---------------------------------
// 1. validateVote() Tests
// ---------------------------------
console.log('\nRunning tests for validateVote()...');
const TEST_CANDIDATES = ['A', 'B', 'C'];

test('should return valid for a correct ballot', () => {
  const ballot = ['A', 'C', 'B'];
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(result, { valid: true, error: null }, 'Valid ballot failed');
});

test('should return invalid for a duplicate candidate', () => {
  const ballot = ['A', 'B', 'A'];
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(
    result,
    {
      valid: false,
      error: 'Duplicate found: ballot contains repeated option rankings.',
    },
    'Duplicate candidate check failed'
  );
});

test('should return invalid for an unknown candidate', () => {
  const ballot = ['C', 'D', 'A'];
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(
    result,
    {
      valid: false,
      error: `Invalid choice: "D" is not one of the options.`,
    },
    'Unknown candidate check failed'
  );
});

test('should return valid for a partial ballot', () => {
  const ballot = ['B', 'A'];
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(result, { valid: true, error: null }, 'Partial ballot failed');
});

test('should return invalid for a ballot containing a non-string choice', () => {
  const ballot = ['A', 123, 'C']; // 123 is a number, not a string
  const result = validateVote(ballot, TEST_CANDIDATES);
  assertEqual(
    result,
    {
      valid: false,
      error: 'Invalid choice: ballot contains a non-string value.',
    },
    'Non-string choice check failed'
  );
});

// ---------------------------------
// 2. formatBallots() Tests
// ---------------------------------
console.log('\nRunning tests for formatBallots()...');

test('should filter out invalid and malformed ballots', () => {
  const rawVotes = [
    { userId: 'u-1', rankings: ['A', 'B'] }, // Valid
    { userId: 'u-2', rankings: ['B', 'A', 'B'] }, // Invalid (duplicate)
    { userId: 'u-3', rankings: ['C'] }, // Valid
    { userId: 'u-4', rankings: ['D'] }, // Invalid (unknown)
    { userId: 'u-5', rankings: ['A', 'C'] }, // Valid
    { userId: 'u-6', otherProp: 'foo' }, // Malformed (no .rankings)
    null, // Malformed (null vote)
  ];
  const expected = [
    ['A', 'B'],
    ['C'],
    ['A', 'C'],
  ];
  const skipped = [];
  const result = formatBallots(rawVotes, TEST_CANDIDATES, (vote, error) =>
    skipped.push([vote && vote.userId, error])
  );
  assertEqual(result, expected, 'Ballot formatting failed');
  assertEqual(
    skipped,
    [
      ['u-2', 'Duplicate found: ballot contains repeated option rankings.'],
      ['u-4', 'Invalid choice: "D" is not one of the options.'],
      ['u-6', 'Vote is not an object with a rankings array.'],
      [null, 'Vote is not an object with a rankings array.'],
    ],
    'onInvalid was not called for each skipped vote'
  );
});

test('should not write to the console when skipping ballots', () => {
  const originalWarn = console.warn;
  let warned = false;
  console.warn = () => { warned = true; };
  try {
    formatBallots([{ rankings: ['D'] }], TEST_CANDIDATES);
  } finally {
    console.warn = originalWarn;
  }
  assertEqual(warned, false, 'formatBallots wrote to console.warn');
});

test('should return an empty array for empty input', () => {
  const result = formatBallots([], TEST_CANDIDATES);
  assertEqual(result, [], 'Empty input did not return empty array');
});

// ---------------------------------
// 3. tally() Tests
// ---------------------------------
console.log('\nRunning tests for tally()...');
const TEST_CONFIG = {
  maxRounds: 10,
};

test('should find a winner in a single round (clear majority)', () => {
  const ballots = [
    ['A', 'B', 'C'],
    ['A', 'C', 'B'],
    ['B', 'A', 'C'],
    ['A', 'B', 'C'],
  ];
  const results = tally(ballots, TEST_CANDIDATES, TEST_CONFIG);
  assertEqual(results.winner, 'A', 'First-round winner test failed');
  assertEqual(results.rounds.length, 1, 'First-round winner test had >1 round');
  assertEqual(
    results.rounds[0].tally,
    { A: 3, B: 1, C: 0 },
    'First-round tally incorrect'
  );
});

test('should find a winner in multiple rounds (elimination)', () => {
  // This is the example from the README
  const ballots = [
    ['A', 'B', 'C'],
    ['B', 'A', 'C'],
    ['A', 'C', 'B'],
    ['C', 'B', 'A'],
    ['B', 'A', 'C'],
  ];
  const candidates = ['A', 'B', 'C'];
  const results = tally(ballots, candidates, TEST_CONFIG);

  assertEqual(results.winner, 'B', 'Multi-round winner incorrect');
  assertEqual(results.rounds.length, 2, 'Multi-round election rounds incorrect');
  // Check Round 1
  assertEqual(
    results.rounds[0].status,
    'Elimination',
    'Round 1 status incorrect'
  );
  assertEqual(
    results.rounds[0].eliminated,
    ['C'],
    'Round 1 elimination incorrect'
  );
  // Check Round 2
  assertEqual(
    results.rounds[1].status,
    'Winner found',
    'Round 2 status incorrect'
  );
  assertEqual(
    results.rounds[1].tally,
    { A: 2, B: 3 },
    'Round 2 tally incorrect'
  );
});

test('should stop on a tie that earlier rounds cannot break', () => {
  const ballots = [
    ['A', 'B'],
    ['B', 'A'],
  ];
  const candidates = ['A', 'B'];
  const results = tally(ballots, candidates, TEST_CONFIG);
  assertEqual(results.winner, null, 'Tie test did not result in null winner');
  assertEqual(
    results.rounds[results.rounds.length - 1].status,
    'Unresolved tie',
    'Tie test status incorrect'
  );
});

test('should handle exhausted ballots correctly', () => {
  const ballots = [
    ['A', 'B'],
    ['A', 'B'],
    ['B', 'A'],
    ['B', 'A'],
    ['C'], // This ballot will be exhausted after C is eliminated
  ];
  const candidates = ['A', 'B', 'C'];
  const results = tally(ballots, candidates, TEST_CONFIG);

  // Round 1: Tally is {A: 2, B: 2, C: 1}. C is eliminated.
  // C's 1 vote is transferred to "exhausted".
  // Round 2: Tally is {A: 2, B: 2}. This is an unbreakable tie.
  assertEqual(results.winner, null, 'Exhausted ballot test winner incorrect');
  assertEqual(
    results.rounds.length,
    2,
    'Exhausted ballot test round count incorrect'
  );
  assertEqual(
    results.rounds[0].transfers.C.exhausted,
    1,
    'Did not correctly log exhausted ballot transfer'
  );
  assertEqual(
    results.rounds[1].status,
    'Unresolved tie',
    'Exhausted ballot test did not end in a tie'
  );
});

test('should declare a winner once exhausted ballots drop out of the threshold', () => {
  const ballots = [['A'], ['A'], ['B'], ['C'], ['D']];
  const candidates = ['A', 'B', 'C', 'D'];
  const results = tally(ballots, candidates, { tieBreakOrder: ['D', 'C', 'B', 'A'] });

  // Round 1: {A: 2, B: 1, C: 1, D: 1}, threshold 3. D loses the tie by lot and exhausts.
  // Round 2: {A: 2, B: 1, C: 1}, threshold 3. C loses the tie by lot and exhausts.
  // Round 3: {A: 2, B: 1}, 3 continuing, threshold 2. A wins, though short of 3 of all 5 ballots.
  assertEqual(results.winner, 'A', 'Winner on continuing ballots not found');
  assertEqual(results.rounds.length, 3, 'Round count incorrect');
  assertEqual(
    [results.rounds[2].threshold, results.rounds[2].exhausted],
    [2, 2],
    'Final round threshold/exhausted incorrect'
  );
});

test('should not declare a winner when the only option has no votes', () => {
  const results = tally([], ['A'], TEST_CONFIG);
  assertEqual(results.winner, null, 'Zero-vote sole option should not win');
});

test('should default maxRounds when config is omitted', () => {
  const ballots = [
    ['A', 'B', 'C'],
    ['B', 'A', 'C'],
    ['A', 'C', 'B'],
    ['C', 'B', 'A'],
    ['B', 'A', 'C'],
  ];
  const results = tally(ballots, ['A', 'B', 'C']);
  assertEqual(results.winner, 'B', 'Default config winner incorrect');
  assertEqual(results.error, undefined, 'Default config should not hit max rounds');
});

test('should measure the threshold against continuing ballots each round', () => {
  const ballots = [
    ['A'], ['A'], ['A'], ['A'],
    ['B'], ['B'], ['B'],
    ['C'], ['C'],
    ['D'],
  ];
  const results = tally(ballots, ['A', 'B', 'C', 'D'], TEST_CONFIG);

  // Round 1: 10 continuing, threshold 6. D eliminated, its ballot exhausts.
  // Round 2: 9 continuing, threshold 5. C eliminated, its ballots exhaust.
  // Round 3: 7 continuing, threshold 4. A has 4 and wins.
  assertEqual(results.winner, 'A', 'Continuing-ballot winner incorrect');
  assertEqual(results.threshold, 6, 'Top-level threshold should be the first-round threshold');
  assertEqual(results.rounds.length, 3, 'Continuing-ballot round count incorrect');
  assertEqual(
    results.rounds.map((r) => [r.threshold, r.exhausted]),
    [[6, 0], [5, 1], [4, 3]],
    'Per-round threshold/exhausted incorrect'
  );
});

test('should break a last-place tie using the previous round', () => {
  const ballots = [
    ['A'], ['A'], ['A'],
    ['B', 'A'], ['B', 'C'],
    ['C'], ['C'], ['C'],
    ['D', 'B', 'A'],
  ];
  const results = tally(ballots, ['A', 'B', 'C', 'D'], TEST_CONFIG);

  // Round 1: {A: 3, B: 2, C: 3, D: 1}. D eliminated, transfers to B.
  // Round 2: {A: 3, B: 3, C: 3}. B had the fewest in round 1, so only B is eliminated.
  // Round 3: {A: 5, C: 4}. A wins.
  assertEqual(results.rounds[1].eliminated, ['B'], 'Previous-round tie-break eliminated the wrong option');
  assertEqual(results.rounds[1].tieBreak, 'previous_round', 'Tie-break method not recorded');
  assertEqual(results.rounds[2].tally, { A: 5, C: 4 }, 'Final tally incorrect');
  assertEqual(results.winner, 'A', 'Previous-round tie-break winner incorrect');
});

test('should batch-eliminate options tied at zero votes', () => {
  // Round 1: {A: 2, B: 2, C: 1, D: 0, E: 0}. D and E have no votes, so eliminating them
  // together moves no ballots and is identical to eliminating them one at a time.
  const results = tally([['A'], ['A'], ['B'], ['B'], ['C', 'A']], ['A', 'B', 'C', 'D', 'E'], TEST_CONFIG);
  assertEqual(results.rounds[0].eliminated, ['D', 'E'], 'Zero-vote batch elimination incorrect');
  assertEqual(results.rounds[0].tieBreak, 'batch', 'Batch tie-break not recorded');
  assertEqual(results.winner, 'A', 'Zero-vote batch winner incorrect');
});

test('should not batch-eliminate tied options that hold votes', () => {
  // Round 1: {A: 4, B: 3, C: 1, D: 1}. C and D cannot catch B, but eliminating them together
  // would skip a round that a later previous-round tie-break could depend on.
  const results = tally(
    [['A'], ['A'], ['A'], ['A'], ['B'], ['B'], ['B'], ['C'], ['D']],
    ['A', 'B', 'C', 'D'],
    TEST_CONFIG
  );
  assertEqual(results.winner, null, 'Tie with votes should not be batch-eliminated');
  assertEqual(results.rounds[0].status, 'Unresolved tie', 'Unresolved tie status incorrect');
  assertEqual(results.rounds[0].eliminated, [], 'Unresolved tie should eliminate nothing');
  assertEqual(
    results.error,
    'Tie for last place between C, D cannot be broken by earlier rounds. Pass config.tieBreakOrder (see drawTieBreakOrder()) to resolve it.',
    'Unresolved tie error incorrect'
  );
});

test('should use tieBreakOrder when earlier rounds cannot break a tie', () => {
  const results = tally([['A', 'B'], ['B', 'A']], ['A', 'B'], { tieBreakOrder: ['B', 'A'] });
  assertEqual(results.rounds[0].eliminated, ['B'], 'tieBreakOrder eliminated the wrong option');
  assertEqual(results.rounds[0].tieBreak, 'tie_break_order', 'tieBreakOrder method not recorded');
  assertEqual(results.winner, 'A', 'tieBreakOrder winner incorrect');
});

test('should reject a tieBreakOrder that does not list every option', () => {
  let message = null;
  try {
    tally([['A']], ['A', 'B'], { tieBreakOrder: ['A'] });
  } catch (error) {
    message = error.message;
  }
  assertEqual(message, 'config.tieBreakOrder must be an array listing every option.', 'Incomplete tieBreakOrder did not throw');
});

// ---------------------------------
// 4. drawTieBreakOrder() Tests
// ---------------------------------
console.log('\nRunning tests for drawTieBreakOrder()...');

test('should return a shuffled copy containing every option once', () => {
  const options = ['A', 'B', 'C', 'D', 'E'];
  const order = drawTieBreakOrder(options);
  assertEqual([...order].sort(), options, 'Draw is not a permutation of the options');
  assertEqual(options, ['A', 'B', 'C', 'D', 'E'], 'Draw mutated the input');
});

test('should use an injected random source deterministically', () => {
  // Always picking index 0 moves each element to the front in turn: a rotation.
  assertEqual(drawTieBreakOrder(['A', 'B', 'C', 'D'], () => 0), ['B', 'C', 'D', 'A'], 'Injected source not used');
});

test('should draw every ordering with equal probability', () => {
  // 6 orderings of 3 options, 6000 draws: expect ~1000 each (sd ~29). A 200 margin is ~7 sd.
  const counts = {};
  for (let i = 0; i < 6000; i++) {
    const key = drawTieBreakOrder(['A', 'B', 'C']).join('');
    counts[key] = (counts[key] || 0) + 1;
  }
  assertEqual(Object.keys(counts).length, 6, 'Not every ordering was drawn');
  for (const [order, count] of Object.entries(counts)) {
    if (Math.abs(count - 1000) > 200) {
      throw new Error(`Ordering ${order} drawn ${count} times, expected about 1000`);
    }
  }
});

test('should produce an order tally() accepts, resolving ties earlier rounds cannot', () => {
  const options = ['A', 'B'];
  const results = tally([['A', 'B'], ['B', 'A']], options, { tieBreakOrder: drawTieBreakOrder(options) });
  assertEqual(results.rounds[0].tieBreak, 'tie_break_order', 'Drawn order was not used');
  assertEqual(results.winner !== null, true, 'Drawn order did not resolve the tie');
});

// ---------------------------------
// Final Summary
// ---------------------------------
console.log('\n---------------------------------');
console.log('         Test Summary');
console.log('---------------------------------');
console.log(`  Total Tests: ${testCount}`);
if (passCount === testCount) {
  console.log(`\x1b[32m  Passed:      ${passCount}\x1b[0m`); // Green
  console.log('\x1b[32m\n  All tests passed! ✨\x1b[0m');
} else {
  console.log(`\x1b[32m  Passed:      ${passCount}\x1b[0m`); // Green
  console.log(`\x1b[31m  Failed:      ${testCount - passCount}\x1b[0m`); // Red
  console.log('\x1b[31m\n  Some tests failed.\x1b[0m');
  process.exitCode = 1; // Fail `npm test` so CI does not publish a broken build
}
console.log('---------------------------------\n');